# Generated by Django 6.0.5 on 2026-05-18 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isp', models.CharField(max_length=100)),
                ('download_mbps', models.DecimalField(decimal_places=2, max_digits=8)),
                ('upload_mbps', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ping_ms', models.DecimalField(decimal_places=2, max_digits=8)),
                ('jitter_ms', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('test_datetime', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speed_tests', to='core.site')),
            ],
            options={
                'ordering': ['-test_datetime'],
            },
        ),
    ]
